---
# This Github workflow will run jobs to build java-app.
name: spring-petclinic
#test
on:
  schedule:
  - cron: '*/15 * * * *' # every 15 minutes
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
permissions:
  pull-requests: write

jobs:
  minimal:
    uses: ploigos/ploigos-github-workflows/.github/workflows/minimal.yaml@bugtest
    secrets: inherit
