---
# This Github workflow will run jobs to build java-app.
name: spring-petclinic
#test
on:
  schedule:
  - cron: '0 0 * * *' # every night at 12:00AM UTC
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
permissions:
  pull-requests: write

jobs:
  minimal:
    uses: ploigos/ploigos-github-workflows/.github/workflows/minimal.yaml@36-add-support-for-psr-report-step
    secrets: inherit
