---
# This Github workflow will run jobs to build java-app.
name: spring-petclinic-minimal

on:
  schedule:
  - cron: '0 0 * * *' # every night at 12:00AM UTC
  workflow_dispatch:

jobs:
  minimal:
    uses: ploigos/ploigos-github-workflows/.github/workflows/minimal.yaml@main
    secrets: inherit
